/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.isimon.drewdom.gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import pl.isimon.drewdom.Mebel;
import pl.isimon.drewdom.Pracownik;
import pl.isimon.drewdom.Zamowienie;

/**
 *
 * @author Simon
 * @version 0.0.0.2
 * 
 */
public class DrewDom extends javax.swing.JFrame {

    /**
     * Creates new form DrewDom
     */
    public Zamowienie zamowienie;
    public Pracownik pracownik;
    public Mebel mebel;
    
    public DrewDom() {
        zamowienie = new Zamowienie();
        pracownik = new Pracownik();
        mebel = new Mebel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Changelog = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        changelogPanel = new javax.swing.JEditorPane();
        tabPanel = new javax.swing.JTabbedPane();
        gZamowienie1 = new pl.isimon.drewdom.gui.GZamowienieList(zamowienie.getData());
        gPracownik1 = new pl.isimon.drewdom.gui.GPracownik(pracownik.getData());
        gMebleLista1 = new pl.isimon.drewdom.gui.GMebleLista(mebel.getData());
        tollBar = new javax.swing.JToolBar();
        buttonChangelog = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        Changelog.setMinimumSize(new java.awt.Dimension(640, 480));

        jLabel1.setText("Changelog:");

        changelogPanel.setContentType("text/html"); // NOI18N
        changelogPanel.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n      \r<ul>\n                <li>\n                     0.0.0.1 2012-07-18\n                     <ul>\n                         <li>- panel lista zamowien</li>\n                         <li>- panel pracownik</li>\n                         <li>- panel lista mebli</li>\n                     </ul>\n                </li>\n            </ul>\n    </p>\r\n  </body>\r\n</html>\r\n");
        jScrollPane2.setViewportView(changelogPanel);
        changelogPanel.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout ChangelogLayout = new javax.swing.GroupLayout(Changelog.getContentPane());
        Changelog.getContentPane().setLayout(ChangelogLayout);
        ChangelogLayout.setHorizontalGroup(
            ChangelogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangelogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChangelogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addGroup(ChangelogLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ChangelogLayout.setVerticalGroup(
            ChangelogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangelogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DrewDom ver 0.0.0.1");
        setName("DrewDom ver. 0.0.0.1"); // NOI18N

        tabPanel.addTab("Zamowienia", gZamowienie1);
        tabPanel.addTab("Pracownicy", gPracownik1);
        tabPanel.addTab("Meble", gMebleLista1);

        tollBar.setRollover(true);

        buttonChangelog.setText("Changelog");
        buttonChangelog.setFocusable(false);
        buttonChangelog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonChangelog.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonChangelog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangelogActionPerformed(evt);
            }
        });
        tollBar.add(buttonChangelog);

        jMenu1.setText("File");
        menu.add(jMenu1);

        jMenu2.setText("Edit");
        menu.add(jMenu2);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(tollBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tollBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabPanel.getAccessibleContext().setAccessibleName("Zamowienia");
        tabPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChangelogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangelogActionPerformed
        // TODO add your handling code here:
        Changelog.setVisible(true);
    }//GEN-LAST:event_buttonChangelogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrewDom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrewDom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrewDom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrewDom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrewDom().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Changelog;
    private javax.swing.JButton buttonChangelog;
    private javax.swing.JEditorPane changelogPanel;
    private pl.isimon.drewdom.gui.GMebleLista gMebleLista1;
    private pl.isimon.drewdom.gui.GPracownik gPracownik1;
    private pl.isimon.drewdom.gui.GZamowienieList gZamowienie1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JToolBar tollBar;
    // End of variables declaration//GEN-END:variables
}
