/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.isimon.drewdom.gui;

import java.util.ArrayList;
import pl.isimon.drewdom.Mebel;

/**
 *
 * @author Simon
 */
public class GMebleLista extends javax.swing.JPanel {

    /**
     * Creates new form GMebleLista
     */
    public GMebleLista() {
        initComponents();
    }
    
    public GMebleLista(ArrayList<Mebel> lista) {
        initComponents();
        ((TableModelMebleLista)tabelaMeble.getModel()).setModelData(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMeble = new javax.swing.JTable();
        buttonNowy = new javax.swing.JButton();
        buttonEdycja = new javax.swing.JButton();
        buttonPodglad = new javax.swing.JButton();
        buttonUsun = new javax.swing.JButton();
        textSzukajKod = new javax.swing.JTextField();
        textSzukajNazwa = new javax.swing.JTextField();
        labelSzukajKod = new javax.swing.JLabel();
        labelSzukajNazwa = new javax.swing.JLabel();
        buttonSzukaj = new javax.swing.JButton();

        tabelaMeble.setModel(new TableModelMebleLista());
        jScrollPane1.setViewportView(tabelaMeble);

        buttonNowy.setText("Nowy");

        buttonEdycja.setText("Edycja");

        buttonPodglad.setText("Podgląd");

        buttonUsun.setText("Usuń");

        textSzukajKod.setText("jTextField1");

        textSzukajNazwa.setText("jTextField2");

        labelSzukajKod.setText("jLabel1");

        labelSzukajNazwa.setText("jLabel2");

        buttonSzukaj.setText("szukaj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonNowy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonPodglad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEdycja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUsun))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSzukajKod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textSzukajKod, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelSzukajNazwa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textSzukajNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSzukaj)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSzukajKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSzukajNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSzukaj)
                    .addComponent(labelSzukajNazwa)
                    .addComponent(labelSzukajKod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNowy)
                    .addComponent(buttonEdycja)
                    .addComponent(buttonPodglad)
                    .addComponent(buttonUsun))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdycja;
    private javax.swing.JButton buttonNowy;
    private javax.swing.JButton buttonPodglad;
    private javax.swing.JButton buttonSzukaj;
    private javax.swing.JButton buttonUsun;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelSzukajKod;
    private javax.swing.JLabel labelSzukajNazwa;
    private javax.swing.JTable tabelaMeble;
    private javax.swing.JTextField textSzukajKod;
    private javax.swing.JTextField textSzukajNazwa;
    // End of variables declaration//GEN-END:variables
}
