/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.isimon.drewdom.gui;

import java.awt.Dimension;
import pl.isimon.drewdom.gui.models.TableModelMebleLista;
import java.util.ArrayList;
import pl.isimon.drewdom.Mebel;
import pl.isimon.drewdom.gui.utils.TableColumnAdjuster;

/**
 *
 * @author Simon
 */
public class GMebleLista extends javax.swing.JPanel {

    private TableModelMebleLista tableModelMebleLista;
    private Mebel mebel;
    private ArrayList<Mebel> lista = null;
    private TableColumnAdjuster tca;
    /**
     * Creates new form GMebleLista
     */
    public GMebleLista() {
        initComponents();
        mebel = new Mebel();
        tca = new TableColumnAdjuster(tabelaMeble);
        tableModelMebleLista = (TableModelMebleLista) tabelaMeble.getModel();
    }
    
    public GMebleLista(ArrayList<Mebel> lista) {
        initComponents();
        ((TableModelMebleLista)tabelaMeble.getModel()).setModelData(lista);
        previewMebel.setMinimumSize(new Dimension(900,720));
        gMebelNowy1.setMinimumSize(new Dimension(880,700));
    }
    
    public void loadData(){
        if(lista == null) lista = new ArrayList();
        lista = mebel.getData();
        tableModelMebleLista.setModelData(lista);
        tca.adjustColumns();
    }
    
    private void szukaj(){
        tableModelMebleLista.setModelData(mebel.getData(textSzukajNumer.getText(), textSzukajNazwa.getText(), textSzukajKod.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previewMebel = new javax.swing.JFrame();
        gMebelNowy1 = new pl.isimon.drewdom.gui.GMebelNowy();
        buttonPZapisz = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMeble = new javax.swing.JTable();
        buttonEdycja = new javax.swing.JButton();
        buttonPodglad = new javax.swing.JButton();
        buttonUsun = new javax.swing.JButton();
        textSzukajNumer = new javax.swing.JTextField();
        textSzukajNazwa = new javax.swing.JTextField();
        labelSzukajKod = new javax.swing.JLabel();
        labelSzukajNazwa = new javax.swing.JLabel();
        buttonSzukaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textSzukajKod = new javax.swing.JTextField();

        previewMebel.setMinimumSize(new java.awt.Dimension(700, 600));

        gMebelNowy1.setMinimumSize(new java.awt.Dimension(620, 560));

        buttonPZapisz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/filesave.png"))); // NOI18N
        buttonPZapisz.setText("Zapisz");
        buttonPZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPZapiszActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout previewMebelLayout = new javax.swing.GroupLayout(previewMebel.getContentPane());
        previewMebel.getContentPane().setLayout(previewMebelLayout);
        previewMebelLayout.setHorizontalGroup(
            previewMebelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previewMebelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(previewMebelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gMebelNowy1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, previewMebelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonPZapisz)))
                .addContainerGap())
        );
        previewMebelLayout.setVerticalGroup(
            previewMebelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previewMebelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gMebelNowy1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPZapisz)
                .addContainerGap())
        );

        tabelaMeble.setAutoCreateRowSorter(true);
        tabelaMeble.setModel(new TableModelMebleLista());
        jScrollPane1.setViewportView(tabelaMeble);

        buttonEdycja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/editpaste.png"))); // NOI18N
        buttonEdycja.setText("Edycja");
        buttonEdycja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEdycjaActionPerformed(evt);
            }
        });

        buttonPodglad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/filefind.png"))); // NOI18N
        buttonPodglad.setText("Podgląd");
        buttonPodglad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPodgladActionPerformed(evt);
            }
        });

        buttonUsun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/edittrash.png"))); // NOI18N
        buttonUsun.setText("Usuń");
        buttonUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsunActionPerformed(evt);
            }
        });

        textSzukajNumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSzukajNumerActionPerformed(evt);
            }
        });

        textSzukajNazwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSzukajNazwaActionPerformed(evt);
            }
        });

        labelSzukajKod.setText("Numer");

        labelSzukajNazwa.setText("Nazwa");

        buttonSzukaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/viewmag.png"))); // NOI18N
        buttonSzukaj.setText("Szukaj");
        buttonSzukaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSzukajActionPerformed(evt);
            }
        });

        jLabel1.setText("Kod");

        textSzukajKod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSzukajKodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSzukajKod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textSzukajNumer, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelSzukajNazwa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textSzukajNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textSzukajKod, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSzukaj))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonPodglad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEdycja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUsun)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonEdycja, buttonPodglad, buttonSzukaj, buttonUsun});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textSzukajKod, textSzukajNazwa, textSzukajNumer});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSzukajNumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSzukajNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSzukaj)
                    .addComponent(labelSzukajNazwa)
                    .addComponent(labelSzukajKod)
                    .addComponent(jLabel1)
                    .addComponent(textSzukajKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUsun)
                    .addComponent(buttonEdycja)
                    .addComponent(buttonPodglad))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsunActionPerformed
          // TODO add your handling code here:
        int selection = tabelaMeble.getSelectedRow();
        if(selection!=-1){
            Mebel m = tableModelMebleLista.getMebel(selection);
            lista.remove(m);
            mebel.usun(m);
            tableModelMebleLista.setModelData(lista);
        }
    }//GEN-LAST:event_buttonUsunActionPerformed

    private void buttonPodgladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPodgladActionPerformed
        int selection = tabelaMeble.getSelectedRow();
        if(selection!=-1){
            Mebel m = tableModelMebleLista.getMebel(selection);
            gMebelNowy1.setPreview(true);
            previewMebel.setVisible(true);
            gMebelNowy1.loadData(m);
            if(gMebelNowy1.getPreview()) buttonPZapisz.setEnabled(false);
        }
    }//GEN-LAST:event_buttonPodgladActionPerformed

    private void buttonEdycjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEdycjaActionPerformed
        int selection = tabelaMeble.getSelectedRow();
        buttonPZapisz.setEnabled(true);
        gMebelNowy1.setPreview(false);
        if(selection!=-1){
            Mebel m = tableModelMebleLista.getMebel(selection);
            previewMebel.setMinimumSize(new Dimension(900,720));
            previewMebel.setVisible(true);
            gMebelNowy1.edycja = true;
            gMebelNowy1.loadData(m);
        }
    }//GEN-LAST:event_buttonEdycjaActionPerformed

    private void buttonPZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPZapiszActionPerformed
        gMebelNowy1.actionSave();
        gMebelNowy1.edycja = false;
        previewMebel.dispose();
        loadData();
    }//GEN-LAST:event_buttonPZapiszActionPerformed

    private void buttonSzukajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSzukajActionPerformed
        szukaj();
    }//GEN-LAST:event_buttonSzukajActionPerformed

    private void textSzukajNumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSzukajNumerActionPerformed
        szukaj();
    }//GEN-LAST:event_textSzukajNumerActionPerformed

    private void textSzukajNazwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSzukajNazwaActionPerformed
        szukaj();
    }//GEN-LAST:event_textSzukajNazwaActionPerformed

    private void textSzukajKodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSzukajKodActionPerformed
        szukaj();
    }//GEN-LAST:event_textSzukajKodActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdycja;
    private javax.swing.JButton buttonPZapisz;
    private javax.swing.JButton buttonPodglad;
    private javax.swing.JButton buttonSzukaj;
    private javax.swing.JButton buttonUsun;
    private pl.isimon.drewdom.gui.GMebelNowy gMebelNowy1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelSzukajKod;
    private javax.swing.JLabel labelSzukajNazwa;
    private javax.swing.JFrame previewMebel;
    private javax.swing.JTable tabelaMeble;
    private javax.swing.JTextField textSzukajKod;
    private javax.swing.JTextField textSzukajNazwa;
    private javax.swing.JTextField textSzukajNumer;
    // End of variables declaration//GEN-END:variables
}
