/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.isimon.drewdom.gui;

import pl.isimon.drewdom.gui.models.TableModelOkucie;
import java.util.ArrayList;
import javax.swing.table.TableColumn;
import pl.isimon.drewdom.Okucie;
import pl.isimon.drewdom.gui.utils.TableColumnAdjuster;

/**
 *
 * @author Simon
 */
public class GOkucia extends javax.swing.JPanel {

    /**
     * Creates new form GOkucia
     */
    private boolean edycja = false;
    private TableModelOkucie tmo;
    private Okucie okucie;
    private TableColumnAdjuster tca;
    public GOkucia() {
        initComponents();
    }
    
    public GOkucia(ArrayList<Okucie> lista){
        this();
        okucie = new Okucie();
        tmo = (TableModelOkucie) tableOkucia.getModel();
        tmo.setModelData(lista);
        TableColumn col;
        tca = new TableColumnAdjuster(tableOkucia);
        tca.adjustColumns();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableOkucia = new javax.swing.JTable();
        textNazwa = new javax.swing.JTextField();
        labelNazwa = new javax.swing.JLabel();
        buttonZapisz = new javax.swing.JButton();
        buttonUsun = new javax.swing.JButton();
        buttonEdytuj = new javax.swing.JButton();
        buttonAnuluj = new javax.swing.JButton();

        tableOkucia.setModel(new TableModelOkucie());
        tableOkucia.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tableOkucia);

        labelNazwa.setText("Nazwa");

        buttonZapisz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/button_ok.png"))); // NOI18N
        buttonZapisz.setText("Dodaj");
        buttonZapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZapiszActionPerformed(evt);
            }
        });

        buttonUsun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/edittrash.png"))); // NOI18N
        buttonUsun.setText("Usuń");
        buttonUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsunActionPerformed(evt);
            }
        });

        buttonEdytuj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/editpaste.png"))); // NOI18N
        buttonEdytuj.setText("Edytuj");
        buttonEdytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEdytujActionPerformed(evt);
            }
        });

        buttonAnuluj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/button_cancel.png"))); // NOI18N
        buttonAnuluj.setText("Anuluj");
        buttonAnuluj.setEnabled(false);
        buttonAnuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAnulujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNazwa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonZapisz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEdytuj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAnuluj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUsun)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUsun)
                    .addComponent(buttonAnuluj)
                    .addComponent(buttonEdytuj)
                    .addComponent(buttonZapisz)
                    .addComponent(textNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNazwa))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonZapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZapiszActionPerformed
        okucie.nazwa = textNazwa.getText();
        if(edycja){
            okucie.edytuj(okucie);
            edycja = false;
            buttonZapisz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/button_ok.png")));
            buttonZapisz.setText("Dodaj");
            buttonAnuluj.setEnabled(false);
        } else {
            okucie.dodaj(okucie);
        }
        tmo.setModelData(okucie.getData());
        textNazwa.setText("");
    }//GEN-LAST:event_buttonZapiszActionPerformed

    private void buttonEdytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEdytujActionPerformed
        edycja = true;
        okucie = tmo.getOkucie(tableOkucia.getSelectedRow());
        textNazwa.setText(okucie.nazwa);
        buttonAnuluj.setEnabled(true);
        buttonZapisz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/filesave.png")));
        buttonZapisz.setText("Zapisz");
    }//GEN-LAST:event_buttonEdytujActionPerformed

    private void buttonAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAnulujActionPerformed
        textNazwa.setText("");
        edycja = false;
        buttonZapisz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/button_ok.png")));
        buttonZapisz.setText("Dodaj");
        buttonAnuluj.setEnabled(false);
    }//GEN-LAST:event_buttonAnulujActionPerformed

    private void buttonUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsunActionPerformed
        okucie = tmo.getOkucie(tableOkucia.getSelectedRow());
        okucie.usun(okucie);
        tmo.removeOkucie(okucie);
    }//GEN-LAST:event_buttonUsunActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAnuluj;
    private javax.swing.JButton buttonEdytuj;
    private javax.swing.JButton buttonUsun;
    private javax.swing.JButton buttonZapisz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNazwa;
    private javax.swing.JTable tableOkucia;
    private javax.swing.JTextField textNazwa;
    // End of variables declaration//GEN-END:variables
}
