/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.isimon.drewdom.gui;

import pl.isimon.drewdom.gui.models.TableModelZamowieniePozycja;
import pl.isimon.drewdom.gui.models.TableModelMebleLista;
import java.util.ArrayList;
import pl.isimon.drewdom.Mebel;
import pl.isimon.drewdom.Zamowienie;
import pl.isimon.drewdom.ZamowieniePozycja;

/**
 *
 * @author Simon
 */
public class GZamowienieNew extends javax.swing.JPanel {

    /**
     * Creates new form GZamowienieNew
     */
    private Zamowienie zamowienie;
    private TableModelMebleLista tmml;
    private TableModelZamowieniePozycja tmzp;
    private ArrayList<ZamowieniePozycja> zamowienieLista;
    public GZamowienieNew() {
        initComponents();
    }
    
    public GZamowienieNew(ArrayList<Mebel> lista){
        this();
        zamowienieLista = new ArrayList();
        zamowienie = new Zamowienie();
        tmzp = (TableModelZamowieniePozycja)tableZamowienie.getModel();
        tmml = (TableModelMebleLista)tableMeble.getModel();
        tmml.setModelData(lista);
        tmzp.setModelData(zamowienieLista);
    }
    
    public void save(){
        zamowienie.zapiszZamowienie(textNumer.getText(), zamowienieLista, dcDataZamowienia.getDate(), dcDataRealizaji.getDate());
    }
    
    public void clear(){
        zamowienieLista = new ArrayList();
        tmzp.setModelData(zamowienieLista);
        textNumer.setText("");
        dcDataZamowienia.setDate(null);
        dcDataRealizaji.setDate(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableZamowienie = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMeble = new javax.swing.JTable();
        buttonDodaj = new javax.swing.JButton();
        labelSztuk = new javax.swing.JLabel();
        textKod = new javax.swing.JTextField();
        textNazwa = new javax.swing.JTextField();
        textNumer = new javax.swing.JTextField();
        labelNumer = new javax.swing.JLabel();
        dcDataZamowienia = new com.toedter.calendar.JDateChooser();
        dcDataRealizaji = new com.toedter.calendar.JDateChooser();
        labelDataZamowienia = new javax.swing.JLabel();
        labelDataRealizacji = new javax.swing.JLabel();
        buttonSzukaj = new javax.swing.JButton();
        labelKod = new javax.swing.JLabel();
        labelNazwa = new javax.swing.JLabel();
        buttonUsun = new javax.swing.JButton();
        spinnerSztuk = new javax.swing.JSpinner();

        setMinimumSize(new java.awt.Dimension(620, 515));
        setPreferredSize(new java.awt.Dimension(620, 515));

        tableZamowienie.setModel(new TableModelZamowieniePozycja());
        jScrollPane1.setViewportView(tableZamowienie);

        tableMeble.setModel(new TableModelMebleLista());
        jScrollPane2.setViewportView(tableMeble);

        buttonDodaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/button_ok.png"))); // NOI18N
        buttonDodaj.setText("Dodaj");
        buttonDodaj.setFocusPainted(false);
        buttonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDodajActionPerformed(evt);
            }
        });

        labelSztuk.setText("Sztuk");

        textKod.setEnabled(false);

        textNazwa.setEnabled(false);

        labelNumer.setText("Numer zamówienia");

        labelDataZamowienia.setText("Data złożenia zamówienia");

        labelDataRealizacji.setText("Data realizacji");

        buttonSzukaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/viewmag.png"))); // NOI18N
        buttonSzukaj.setText("Szukaj");
        buttonSzukaj.setEnabled(false);

        labelKod.setText("Kod");

        labelNazwa.setText("Nazwa");

        buttonUsun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/edittrash.png"))); // NOI18N
        buttonUsun.setText("Usuń");
        buttonUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsunActionPerformed(evt);
            }
        });

        spinnerSztuk.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9999, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelKod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textKod, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNazwa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSzukaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(buttonUsun))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNumer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNumer, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDataZamowienia))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelDataRealizacji)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcDataRealizaji, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcDataZamowienia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelSztuk)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerSztuk, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDodaj)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonDodaj, buttonSzukaj, buttonUsun});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textNumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelNumer)
                        .addComponent(labelDataZamowienia))
                    .addComponent(dcDataZamowienia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcDataRealizaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataRealizacji))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKod)
                    .addComponent(textKod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNazwa)
                    .addComponent(textNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSzukaj)
                    .addComponent(buttonUsun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDodaj)
                    .addComponent(labelSztuk)
                    .addComponent(spinnerSztuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDodajActionPerformed
        int selection = tableMeble.getSelectedRow();
        int sztuk = (int)spinnerSztuk.getModel().getValue();
        
        if(sztuk!=0 & selection!=-1){
            ZamowieniePozycja poz = new ZamowieniePozycja();
            poz.ilosc = sztuk;
            poz.mebel = tmml.getMebel(selection);
            //zamowienieLista.add(poz);
            tmzp.addZamowieniePozycja(poz);
            spinnerSztuk.getModel().setValue(new Integer(0));
        }
    }//GEN-LAST:event_buttonDodajActionPerformed

    private void buttonUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsunActionPerformed
        ZamowieniePozycja zamp;
        zamp = tmzp.getZamowieniePozycja(tableZamowienie.getSelectedRow());
        zamowienieLista.remove(zamp);
        tmzp.removeZamowieniePozycja(zamp);
    }//GEN-LAST:event_buttonUsunActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDodaj;
    private javax.swing.JButton buttonSzukaj;
    private javax.swing.JButton buttonUsun;
    private com.toedter.calendar.JDateChooser dcDataRealizaji;
    private com.toedter.calendar.JDateChooser dcDataZamowienia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDataRealizacji;
    private javax.swing.JLabel labelDataZamowienia;
    private javax.swing.JLabel labelKod;
    private javax.swing.JLabel labelNazwa;
    private javax.swing.JLabel labelNumer;
    private javax.swing.JLabel labelSztuk;
    private javax.swing.JSpinner spinnerSztuk;
    private javax.swing.JTable tableMeble;
    private javax.swing.JTable tableZamowienie;
    private javax.swing.JTextField textKod;
    private javax.swing.JTextField textNazwa;
    private javax.swing.JTextField textNumer;
    // End of variables declaration//GEN-END:variables
}
