/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.isimon.drewdom.gui;

import pl.isimon.drewdom.gui.models.TableModelZamowienie;
import java.awt.print.PrinterException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import pl.isimon.drewdom.Zamowienie;
import pl.isimon.drewdom.gui.utils.TableColumnAdjuster;

/**
 *
 * @author Simon
 */
public class GZamowienieList extends javax.swing.JPanel {

    /**
     * Creates new form GZamowienie
     */
    private Zamowienie zamowienie;
    private TableModelZamowienie tmz;
    private ArrayList<Zamowienie> lista = null;
    private TableColumnAdjuster tca;
    
    public GZamowienieList() {
        initComponents();
        zamowienie = new Zamowienie();
        tmz = (TableModelZamowienie)TableZamowienie.getModel();
        tca = new TableColumnAdjuster(TableZamowienie);
    }
    
//    public void setData(ArrayList<Zamowienie> lista){
//        tmz.setModelData(lista);
//    }
    
    public void loadData() {
        if (lista == null) lista = new ArrayList();
        lista = zamowienie.getData();
        tmz.setModelData(lista);
        tca.adjustColumns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        framePreview = new javax.swing.JFrame();
        panelZamowieniePreview = new pl.isimon.drewdom.gui.GZamowieniePreview();
        frameEdycja = new javax.swing.JFrame();
        panelZamowienie = new pl.isimon.drewdom.gui.GZamowienieNew();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableZamowienie = new javax.swing.JTable();
        buttonPodglad = new javax.swing.JButton();
        buttonRealizacja = new javax.swing.JButton();
        buttonNowe = new javax.swing.JButton();
        buttonDrukuj = new javax.swing.JButton();
        buttonUsun = new javax.swing.JButton();

        framePreview.setMinimumSize(new java.awt.Dimension(575, 500));

        javax.swing.GroupLayout framePreviewLayout = new javax.swing.GroupLayout(framePreview.getContentPane());
        framePreview.getContentPane().setLayout(framePreviewLayout);
        framePreviewLayout.setHorizontalGroup(
            framePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePreviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelZamowieniePreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        framePreviewLayout.setVerticalGroup(
            framePreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(framePreviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelZamowieniePreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frameEdycja.setMinimumSize(new java.awt.Dimension(640, 540));

        javax.swing.GroupLayout frameEdycjaLayout = new javax.swing.GroupLayout(frameEdycja.getContentPane());
        frameEdycja.getContentPane().setLayout(frameEdycjaLayout);
        frameEdycjaLayout.setHorizontalGroup(
            frameEdycjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEdycjaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelZamowienie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        frameEdycjaLayout.setVerticalGroup(
            frameEdycjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEdycjaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelZamowienie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setPreferredSize(new java.awt.Dimension(620, 400));

        TableZamowienie.setModel(new pl.isimon.drewdom.gui.models.TableModelZamowienie());
        TableZamowienie.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(TableZamowienie);

        buttonPodglad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/filefind.png"))); // NOI18N
        buttonPodglad.setText("Podgląd");
        buttonPodglad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPodgladActionPerformed(evt);
            }
        });

        buttonRealizacja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/lock.png"))); // NOI18N
        buttonRealizacja.setText("Zrealizowane");
        buttonRealizacja.setEnabled(false);

        buttonNowe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/editpaste.png"))); // NOI18N
        buttonNowe.setText("Edytuj");
        buttonNowe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNoweActionPerformed(evt);
            }
        });

        buttonDrukuj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/fileprint.png"))); // NOI18N
        buttonDrukuj.setText("Drukuj");
        buttonDrukuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDrukujActionPerformed(evt);
            }
        });

        buttonUsun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pl/isimon/drewdom/gui/images/x16/edittrash.png"))); // NOI18N
        buttonUsun.setText("Usun");
        buttonUsun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonNowe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUsun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDrukuj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(buttonRealizacja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPodglad)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonDrukuj, buttonNowe, buttonPodglad, buttonRealizacja, buttonUsun});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonNowe)
                    .addComponent(buttonUsun)
                    .addComponent(buttonDrukuj)
                    .addComponent(buttonPodglad)
                    .addComponent(buttonRealizacja))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDrukujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDrukujActionPerformed
        try {
            TableZamowienie.print();
        } catch (PrinterException ex) {
            Logger.getLogger(GZamowienieList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonDrukujActionPerformed

    private void buttonPodgladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPodgladActionPerformed
        framePreview.setVisible(true);
        Zamowienie z = tmz.getZamowienie(TableZamowienie.getSelectedRow());
        panelZamowieniePreview.loadData(z);
    }//GEN-LAST:event_buttonPodgladActionPerformed

    private void buttonUsunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsunActionPerformed
        int selection = TableZamowienie.getSelectedRow();
        if(selection!=-1){
            zamowienie = tmz.getZamowienie(selection);
            zamowienie.usun(zamowienie);
            tmz.removeZamowienie(zamowienie);
        }
    }//GEN-LAST:event_buttonUsunActionPerformed

    private void buttonNoweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNoweActionPerformed
        int selection = TableZamowienie.getSelectedRow();
        if(selection!=-1){
            Zamowienie z = tmz.getZamowienie(selection);
            panelZamowienie.loadData(z);
            panelZamowienie.setEdycja(true);
            frameEdycja.setVisible(true);
        }
    }//GEN-LAST:event_buttonNoweActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableZamowienie;
    private javax.swing.JButton buttonDrukuj;
    private javax.swing.JButton buttonNowe;
    private javax.swing.JButton buttonPodglad;
    private javax.swing.JButton buttonRealizacja;
    private javax.swing.JButton buttonUsun;
    private javax.swing.JFrame frameEdycja;
    private javax.swing.JFrame framePreview;
    private javax.swing.JScrollPane jScrollPane1;
    private pl.isimon.drewdom.gui.GZamowienieNew panelZamowienie;
    private pl.isimon.drewdom.gui.GZamowieniePreview panelZamowieniePreview;
    // End of variables declaration//GEN-END:variables

    
}
