/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.isimon.drewdom.gui;

import java.awt.Color;

/**
 *
 * @author Simon
 */
public class PanelCellZadania extends javax.swing.JPanel {

    /**
     * Creates new form panelCellZadania
     */
    public PanelCellZadania() {
        initComponents();
    }
    
    public PanelCellZadania(boolean c1,boolean c2,boolean c3){
        this();
        cb1.setSelected(c1);
        cb2.setSelected(c2);
        cb3.setSelected(c3);
    }
    
    public void setSelection(boolean c1,boolean c2,boolean c3){
        cb1.setSelected(c1);
        cb2.setSelected(c2);
        cb3.setSelected(c3);
    }
    
    public void setSelectionColor(Color bg,Color fg){
        this.setBackground(bg);
        this.setForeground(fg);
        cb1.setBackground(bg);
        cb1.setForeground(fg);
        cb2.setBackground(bg);
        cb2.setForeground(fg);
        cb3.setBackground(bg);
        cb3.setForeground(fg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));

        cb1.setText("Klej");

        cb2.setText("Piła");

        cb3.setText("CnC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cb1)
                .addComponent(cb2)
                .addComponent(cb3))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    // End of variables declaration//GEN-END:variables
}
